site_name: "Portfolio"

theme:
  name: material
  language: es
  logo: images/logo.png        
  favicon: images/portada.svg

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - header.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips
    - announce.dismiss

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys

extra_css:
  - styles/extra.css
